web:
    container_name: widmann_web
    image: nginx:latest
    ports:
        - "8088:80"
    volumes:
        - ./src:/widmann
        - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
php:
    container_name: widmann_php
    image: php:7-fpm
    volumes:
        - ./src:/widmann